import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';
import './globals.css';
import { Header } from '@/components';

const roboto = Roboto({
  subsets: ['latin'],
  weight: ['100', '400', '700'],
  preload: false,
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${roboto.className} antialiased h-full w-full overflow-hidden`}>
        <Header />
        <main>{children}</main>
      </body>
    </html>
  );
}
